### ISSUE TITLE
Unable to install on TB 115.0b2 (64-bit)

### ISSUE THREAD

**Issue by cathcam** [voccs/folderflags#13] opened 2023-06-15 18:26 UTC
Thunderbird will no longer allow this to be installed via Add-On & Themes, or by drag and drop using the local zip file.

**Comment by RealRaven2000** [comment] 2023-06-16 12:09
It's caused by trying to access the language bundle via the line:
`var msgrBundle = document.getElementById("bundle_messenger");`

Luckily I found a function `getStringWithFolderNameFromBundle()` in [nsIMsgFolder.idl](https://searchfox.org/comm-central/rev/0a8a9a51ec7ff330d93ac06b6fe02f4e95be57e1/mailnews/base/public/nsIMsgFolder.idl#632) that gets the translated names for these special folders. I made a patched version (tested in Tb 115.0b2), see below:

[folderflags-1.6pre4.zip](https://github.com/voccs/folderflags/files/11770004/folderflags-1.6pre4.zip)

![image](https://github.com/voccs/folderflags/assets/6314674/838261f6-4403-439e-b1d1-a84c28adb798)

To test the version above, download the zip file, drag into Thunderbird Add-ons Manager, do not extract contents or if won't install.

**Comment by RealRaven2000** [comment] 2023-06-16 12:36
I made a fork and PR, hopefully the orginal author of this add-on will see it and marge into his master branch.

**Comment by cathcam** [comment] 2023-06-16 13:08
> I made a fork and PR, hopefully the orginal author of this add-on will see it and marge into his master branch. (I am not that familiar with Github)

Thank you, yes this works great.

**Comment by voccs** [comment] 2023-06-19 17:04
> I made a fork and PR, hopefully the orginal author of this add-on will see it and marge into his master branch. (I am not that familiar with Github)

I didn't see a PR, so I merged in your commit from your fork and published a new version.  Thanks for the quick work!

**Closed** 2023-06-19 17:04 UTC

**Comment by RealRaven2000** [comment] 2023-06-19 20:54
> > I made a fork and PR, hopefully the orginal author of this add-on will see it and marge into his master branch. (I am not that familiar with Github)
> 
> I didn't see a PR, so I merged in your commit from your fork and published a new version. Thanks for the quick work!

thanks! I didn't quite get the git workflow, but I tried (forked on my own github and committed there). Thanks for including my patch.
